### ISSUE TITLE
feature: add F-Score in the stock ranking

### ISSUE THREAD

**Issue by shivamsouravjha** [shivamsouravjha/stock-backend#1]
* Implementing [F-Score](https://www.anderson.ucla.edu/sites/default/files/documents/areas/prg/asam/2019/F-Score.pdf) rating in project.

# Value Investing: Using the Piotroski F-Score to Identify Winning Stocks

This README provides a simplified explanation of Joseph D. Piotroski's research paper titled **"Value Investing: The Use of Historical Financial Statement Information to Separate Winners from Losers."** The paper introduces the **Piotroski F-Score**, a scoring system that helps investors identify undervalued stocks with strong financial health.

---

## Introduction

Value investing involves buying stocks that appear undervalued based on financial ratios like the **book-to-market (BM) ratio**. However, not all high BM stocks are good investments—some are financially distressed and continue to underperform.

**Objective of the Study:**

- **Enhance value investing** by incorporating fundamental financial analysis.
- Develop a simple scoring system (**Piotroski F-Score**) to separate financially strong firms ("winners") from weak ones ("losers") within the high BM category.

---

## The Piotroski F-Score

The **F-Score** is a **9-point scoring system** based on specific financial criteria derived from a company's financial statements. Each criterion adds 1 point if positive, with a maximum score of 9.

### 1. **Profitability Criteria (4 points)**

- **Positive Return on Assets (ROA):** Is the company profitable?
- **Positive Operating Cash Flow (CFO):** Is the company generating cash from operations?
- **Increase in ROA:** Has profitability improved over the past year?
- **Accruals (CFO > ROA):** Are earnings supported by cash flow, indicating high-quality earnings?

### 2. **Leverage, Liquidity, and Source of Funds (3 points)**

- **Decrease in Leverage:** Has the company's debt relative to assets decreased?
- **Increase in Current Ratio:** Has short-term liquidity improved?
- **No New Equity Issuance:** Has the company avoided diluting shareholders by not issuing new shares?

### 3. **Operating Efficiency Criteria (2 points)**

- **Increase in Gross Margin:** Is the company improving its profit margins?
- **Increase in Asset Turnover:** Is the company generating more sales per asset?

---

## How to Calculate the F-Score

For each criterion:

1. **Evaluate the Condition:** Check if the company meets the criterion based on its financial statements.
2. **Assign Points:** Give 1 point for each positive criterion.
3. **Sum the Points:** Add up all the points to get the F-Score (ranging from 0 to 9).

**Interpretation:**

- **High F-Score (8–9):** Strong financial health; likely to outperform.
- **Low F-Score (0–3):** Weak financial health; may underperform.

---

## Applying the F-Score in Investment Strategy

**Step 1:** Identify high BM (value) stocks.

**Step 2:** Calculate the F-Score for each stock.

**Step 3:** Select stocks with high F-Scores for your portfolio.

**Benefits:**

- **Improved Returns:** Historically, high F-Score stocks have outperformed low F-Score stocks.
- **Risk Management:** Avoids financially distressed companies that might appear undervalued but are poor investments.

---

## Research Findings

- **Sample Size:** Analyzed 14,043 high BM firms from 1976 to 1996.
- **Results:** High F-Score firms significantly outperformed low F-Score firms.
- **Consistency:** The strategy was effective across different sizes and industries.

---

## Practical Example

Imagine you're evaluating two companies, both with high BM ratios:

### Company A:

- **F-Score:** 8
- **Indicators:** Positive profitability, decreasing debt, improving margins.

### Company B:

- **F-Score:** 2
- **Indicators:** Negative earnings, increasing debt, declining efficiency.

**Investment Decision:** Choose Company A for your portfolio due to its high F-Score, indicating strong financial health.

---

## Limitations and Considerations

- **Data Availability:** Requires access to detailed financial statements.
- **Market Changes:** The effectiveness may vary with market conditions.
- **Complementary Analysis:** Consider combining with other analyses (e.g., qualitative factors).

---

## Conclusion

The Piotroski F-Score is a valuable tool for investors seeking to enhance their value investing strategy by focusing on financially strong companies. By systematically applying this scoring system, investors can improve portfolio performance and reduce the risk of investing in financially distressed firms.

---

## References

- **Original Research Paper:** [Value Investing: The Use of Historical Financial Statement Information to Separate Winners from Losers](https://www.anderson.ucla.edu/sites/default/files/documents/areas/prg/asam/2019/F-Score.pdf) by Joseph D. Piotroski.

---

**Comment by naineel1209** [comment]
Hi @shivamsouravjha, can I work on this one?

**Comment by shivamsouravjha** [comment]
Sure @naineel1209 feel free to work on it!

**Comment by naineel1209** [comment]
Thanks @shivamsouravjha! I was going through the codebase and was wondering what should be the value of the `COMPANY_URL` env variable?

**Comment by shivamsouravjha** [comment]
Its for the case when we dont have the data in database so we scrap it out from the source website

**Comment by naineel1209** [comment]
Thanks for your response, Just to clarify, is there any specific site that you are using to scrape the data?

**Comment by shivamsouravjha** [comment]
Just for basic detail like name and etc.

**Comment by naineel1209** [comment]
I meant to ask any specific external API endpoint that I should I set in the environment variable.

**Comment by shivamsouravjha** [comment]
Nope you wont be needing that most of data is fetched from mongodb whose sample of 1 stock dump is present on dump.txt

**Comment by naineel1209** [comment]
Hi @shivamsouravjha, I was working on an issue and created a structure to calculate the F-score, but while accessing the document returned from MongoDB, I encountered a strange problem. When I try to access a key like Net Profit +, the map cannot locate the key, even though it is present.

![image](https://github.com/user-attachments/assets/3b3a5510-47a4-4d9a-9418-afc7fd11883b)

But when I access key like `Total Assets` - then it is being located.

![image](https://github.com/user-attachments/assets/38d65809-e395-497c-9421-93afe05e5aed)

Am I possibly missing something in the code? Here's a link to the relevant part of the code: [Code Link](https://github.com/naineel1209/stock-backend/blob/02e1be0fe60866af0fce9baeb41593b7094725b1/main.go#L301)

**Comment by shivamsouravjha** [comment]
ideally this `Net Profit +` should help you access the map, perhaps there's issue with + sign try replicating the same in a small code section

**Comment by naineel1209** [comment]
Hi @shivamsouravjha,

I was able to resolve the issue of accessing the key `Net Profit +`. The problem occurred because the preceding spaces in keys with a + sign contained a non-breaking space `(NBSP)` instead of a regular space. I've addressed this for now.

![image](https://github.com/user-attachments/assets/31d04ec3-af8a-4ece-bb96-30070c04447e)

However, I encountered another issue today. Some of the stock data in the MongoDB restore document you added to the Git repository has a different structure than expected. For example, under `profitLoss > Net Profit +`, we expect an array of strings, but in some cases, it's an array of objects containing quarterly data.

For HDFC Bank:

![image](https://github.com/user-attachments/assets/81a52f10-7d24-4390-9289-a21fe8fa2483)

There are approximately 199 documents with this issue, while 4,553 documents match the expected format. The remaining documents don't have any data.

![image](https://github.com/user-attachments/assets/d389ca89-2098-441a-884a-15382e174f9c)

**Comment by shivamsouravjha** [comment]
actually the HDFC format is the needed one. Reason is that it has months mentioned. 

There are the keys 

`
  | Mar 2015 | Mar 2016 | Mar 2017 | Mar 2018 | Mar 2019 | Mar 2020 | Mar 2021 | Mar 2022 | Mar 2023 | Mar 2024 | TTM
`

But seems like it is not needed as it can be used as array. 

WIll try update the database! Thanks for pointing this out.
