### ISSUE TITLE
add: unit tests

### ISSUE THREAD

**Issue by shivamsouravjha** [shivamsouravjha/stock-backend#10]

**Comment by shivamsouravjha** [comment]
* current coverage is in ballpark of 17-20%
```
go test -v ./... -coverprofile=coverage.out && gocov convert coverage.out | gocov-xml > coverage.xml
```

**Comment by shivamsouravjha** [comment]
while you're at this make a pipeline that ensures that no test fails in a new pr..also would be great if we can show the coverage of the pr raise.

**Comment by TanishqSingla** [comment]
Due to nature of my work, can only give limited time for open source. Hence adding this draft PR so you can track the progress

**Comment by TanishqSingla** [comment]
My PR is ready, have managed to squeeze out coverage to 74.4%. Functions that are remaining are related to fetching resource from a URL.
And some functions need to be refactored to be tested easily as they currently don't have the callbacks extracted out as callable functions.
