### ISSUE TITLE
add: pipelines

### ISSUE THREAD

**Issue by shivamsouravjha** [shivamsouravjha/stock-backend#11]
* add fmt and builder pipelines

**Comment by shivamsouravjha** [comment]
* a lot of basic build pipelines can be added to ensure the PR raised is correct.

**Comment by mohit-nagaraj** [comment]
Hey I thought to add these cicd workflows, does this suffice ur needs:

- Linting Workflow (.github/workflows/lint.yml)
- Build Workflow (.github/workflows/build.yml)
- Unit and Integration Tests Workflow (.github/workflows/tests.yml) - if needed but ppl use
- Static Analysis Workflow (.github/workflows/static-analysis.yml)
