### ISSUE TITLE
Provision to read environment variables from .env file.

### ISSUE THREAD

**Issue by pratikmane1299** [shivamsouravjha/stock-backend#33]
Currently we have to set environment variables at OS level every time we have to run the project. It would be nice if we could read them from an env file as we would not need to set them every time.

Below is the approach I would prefer to accomplish the same.

We can have a struct named config which has all the environment variables, we can read them in the main function and then pass it to the controllers and services using dependency injection. This will eliminate the need to define global variables for services and controllers instead we can create constructor functions and use them as singleton.

**Comment by shivamsouravjha** [comment]
Understandable and being honest in lot of my projects I use it but here I believe it would be an over kill.

rather I personally put the export files in .env file and source it whenever running the server.


Helps me save time

**Comment by pratikmane1299** [comment]
Cool, no worries.
