### ISSUE TITLE
add : upload xlsx form to cloudinary bucket

### ISSUE THREAD

**Issue by shivamsouravjha** [shivamsouravjha/stock-backend#4]
* implement a feature to upload the xlsx file to cloudinary bucket depending upon the credentials.

**Comment by P-yiush07** [comment]
Heyy, can i work on this ? I want to contribute in hactoberfest

**Comment by shivamsouravjha** [comment]
sure @P-yiush07 you can work on this.

**Comment by P-yiush07** [comment]
> sure @P-yiush07 you can work on this.

can you tell me more about this ? What do you want and how.

**Comment by shivamsouravjha** [comment]
When a xlsx form is uploaded its stored on cloudinary. you can keep the password as env params.


This way every xlsx is saved on cloud bucket.

also the name of the file should be a uuid

**Comment by P-yiush07** [comment]
> When a xlsx form is uploaded its stored on cloudinary. you can keep the password as env params.
> 
> This way every xlsx is saved on cloud bucket.
> 
> also the name of the file should be a uuid

So basically you want me to integrate cloudnary bucket in this to save xlsx form on upload.
Right ?

**Comment by shivamsouravjha** [comment]
Yes, so local you can use your own credentials but on deployment i will update the credentials

**Comment by P-yiush07** [comment]
> Yes, so local you can use your own credentials but on deployment i will update the credentials

@shivamsouravjha Please check the #9 PR
